# Copyright (c) 2026 Daniel Harding - RomanAILabs
#
# Co-Architect: Grok (xAI)
# Collaborators: Cursor, Anthropic Claude (Opus 4.7), Gemini-Flash (Google), ChatGPT-5.4 (OpenAI)
#
# Contact: daniel@romanailabs.com | romanailabs@gmail.com
# Website: https://romanailabs.com
"""Phase 11 — honest R2 Omega n-gram rescue benchmark.

Rationale.
    The Final-Product ``bench-wps`` headline reports the raw
    ``effective_wps`` and segments R2 into exact-state vs rescue. That
    number shows "how much throughput did the rescue contribute on
    this run" -- it does NOT tell you "does the rescue actually match
    sensible prompts to sensible answers, or is it firing on any
    trigram collision?". This script isolates the latter question so
    the rescue quality is auditable independent of decode speed.

Method.
    1. Seed a ZPM index with ~20 hand-written NRL architecture Q&A
       pairs. Each entry carries ``prompt_head`` stamped exactly the
       way the live R5 writeback path in ``gguf.py`` writes it today.
       States are written with the R1 anchor convention, matching
       what ``run_gguf`` persists -- not the R2 Omega-folded state.
       This is important: it faithfully models the production
       write/read mismatch that the rescue path is designed to
       bridge.
    2. For every seed, generate several *rephrasings* (paraphrases,
       question-to-statement rewrites, partial overlaps). These are
       curated by hand, not generated by an LLM, so the baseline is
       human-intelligible.
    3. For every rephrasing, call ``try_omega_native_resolve`` in
       active mode with the rephrased prompt. The primary lookup
       will miss by construction (R2 state != stored R1 state). The
       rescue fires on prompt_head overlap. We record the entry it
       matched so the reviewer can eyeball the rescue quality.
    4. Emit a summary with per-seed rescue rate, the distribution of
       overlap scores, and a full audit trail: query -> matched
       ``prompt_head`` -> reply_text.

What this does NOT measure.
    * Wall-clock throughput. Use ``nrlpy bench-wps <model.gguf>`` for
      that. This script runs on the tiny GGUF fixture -- the LMO is
      trivial and the Omega probe is cheap, so timings here are not
      representative of real-model throughput.
    * End-to-end chat coherence. A rescue serving a sensible
      prompt->reply pair does NOT prove the reply is appropriate for
      every plausible extension of the prompt. That's what Stage-VI
      was for in the non-rescue path; rescues deliberately skip
      bit-symmetry. This script reports rescue semantic quality (via
      prompt_head audit) but cannot prove deep reply-level coherence.
"""

from __future__ import annotations

import argparse
import json
import struct
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path

# Make the in-tree nrlpy source importable without requiring a pip install.
_REPO_ROOT = Path(__file__).resolve().parent.parent
_PKG_SRC = _REPO_ROOT / "nrlpy" / "src"
if _PKG_SRC.is_dir() and str(_PKG_SRC) not in sys.path:
    sys.path.insert(0, str(_PKG_SRC))

from nrlpy import gguf, lmo, zpm  # noqa: E402
from nrlpy.lmo import (  # noqa: E402
    _NGRAM_OVERLAP_THRESHOLD,
    _char_ngrams,
    _ngram_jaccard,
    _ngram_rescue_search,
    try_omega_native_resolve,
)


# --------------------------------------------------------------------------- #
# Hand-curated NRL Q&A seed corpus
# --------------------------------------------------------------------------- #
#
# Each seed is a real architectural question with a real answer grounded
# in the current nrlpy source tree. No invented vocabulary. The
# ``rephrases`` field is the set of prompts we'll fire at the rescue
# path -- a mix of paraphrasing styles (question reorder, contraction,
# topic drop, additional qualifier, statement form).


@dataclass(frozen=True)
class Seed:
    prompt: str
    reply: str
    rephrases: tuple[str, ...]


_SEED_CORPUS: tuple[Seed, ...] = (
    Seed(
        prompt="What is R2 Omega Native Resolve?",
        reply=(
            "R2 is the rung between R1 ZPM and R5 full decode. It runs a "
            "bounded Omega probe over the LMO router graph, folds the "
            "sub-lattice digests into a 256-bit candidate state via "
            "Plane-A.5, and serves the matched ZPM reply if Stage-VI "
            "passes."
        ),
        rephrases=(
            "what's R2 Omega again?",
            "tell me about R2 omega native resolve",
            "how does R2 omega resolve work?",
            "explain R2 omega native resolve in one paragraph",
        ),
    ),
    Seed(
        prompt="What does zpm_threshold_bits control?",
        reply=(
            "zpm_threshold_bits is the Hamming tolerance for ZPM near-"
            "match lookups. distance_bits=0 is an exact hit; "
            "0<distance<=threshold is a near-match. Higher threshold "
            "means more fuzzy matches; 28 is the rewired-mode default."
        ),
        rephrases=(
            "what is zpm_threshold_bits?",
            "how does the zpm threshold bits setting work?",
            "explain zpm threshold bits",
            "what does the zpm_threshold_bits knob do",
        ),
    ),
    Seed(
        prompt="How does Cl(4,0) rotor fit into ZPM verify?",
        reply=(
            "The rotor is a Clifford Cl(4,0) sandwich product with a "
            "scalar s and bivectors b_xy, b_xz, b_xw. zpm.verify() "
            "computes the XOR residual of the candidate and stored "
            "State words; a non-zero residual means bit-symmetry drift "
            "and the entry is demoted."
        ),
        rephrases=(
            "how is Cl(4,0) used in zpm verify?",
            "what's the role of the clifford rotor in verify?",
            "explain cl 4 0 rotor and zpm verify",
        ),
    ),
    Seed(
        prompt="What is the Resolution Ladder?",
        reply=(
            "The Resolution Ladder is the ordered cascade the runner "
            "dispatches each turn through: R0 Muscle Memory, R1 ZPM "
            "nullspace, R2 Omega Native Resolve, prefill-cache, layer-"
            "skip, R5 full decode. Each rung can serve or demote."
        ),
        rephrases=(
            "what are the rungs of the resolution ladder?",
            "tell me about the NRL resolution ladder",
            "explain the resolution ladder",
            "what's the R0 through R5 ladder?",
        ),
    ),
    Seed(
        prompt="What is Muscle Memory (R0)?",
        reply=(
            "R0 Muscle Memory is a byte-identical replay cache keyed "
            "by FNV-1a64 over the rendered prompt bundle. On a hit the "
            "runner returns the previously-generated reply without "
            "touching the decoder."
        ),
        rephrases=(
            "explain muscle memory caching",
            "how does R0 muscle memory work?",
            "what's the muscle memory rung?",
        ),
    ),
    Seed(
        prompt="What does coherence_lane=max-throughput do?",
        reply=(
            "max-throughput enables R2 Omega Native Resolve as an "
            "active token-serving rung. On fast-stable R2 is hard-"
            "locked to shadow-only."
        ),
        rephrases=(
            "what is max-throughput coherence lane?",
            "how does coherence_lane max throughput behave?",
            "explain the max throughput lane",
        ),
    ),
    Seed(
        prompt="How is the LMO absorbed from a GGUF?",
        reply=(
            "absorb_gguf() executes Stages A-I through A-VI: map the "
            "GGUF file, pack each tensor into INT4 tiles, build the "
            "router graph over sub-lattices, write the lmo_anchor "
            "header, and verify byte-parity against libllama when "
            "sovereign."
        ),
        rephrases=(
            "how does gguf absorption work?",
            "explain absorb_gguf",
            "what do stages A-I through A-VI do?",
        ),
    ),
    Seed(
        prompt="What is ZPM nullspace?",
        reply=(
            "The nullspace is the set of stored unity states. Lookup "
            "XORs the query State against every stored state and picks "
            "the minimum Hamming distance. distance=0 is an exact "
            "singularity; within threshold_bits is a near-match."
        ),
        rephrases=(
            "what is the zpm nullspace?",
            "how does zpm nullspace lookup work?",
            "explain zpm nullspace",
        ),
    ),
    Seed(
        prompt="What is the 256-bit State?",
        reply=(
            "A ZPM State is four uint64 words = 256 bits, produced by "
            "zpm.anchor() via four rotated FNV-1a64 passes over the "
            "turn bundle (model_sha | system | history | user | "
            "sampler)."
        ),
        rephrases=(
            "how is the zpm state computed?",
            "what's the 4xu64 state?",
            "explain the 256 bit state",
        ),
    ),
    Seed(
        prompt="What does inversion do in zpm.py?",
        reply=(
            "inversion() is Stage II of the ZPM pipeline: GF(2) row "
            "parity where rows[i] = t[i] ^ (t[i] << 1) ^ "
            "0x9E3779B97F4A7C15. It's the discrete derivative over "
            "Cl(4,0) that feeds the rotor's bivector computation."
        ),
        rephrases=(
            "explain zpm inversion",
            "what is the inversion step?",
            "how does gf 2 row parity work in zpm?",
        ),
    ),
    Seed(
        prompt="Why does Stage-VI skip bit-symmetry for rescued entries?",
        reply=(
            "By construction, an n-gram-rescued entry has stored_state "
            "!= candidate_state (that's why the primary lookup missed). "
            "zpm.verify would always reject it. The rescue audit keeps "
            "tokenizer/UTF-8/blob checks and relies on the overlap "
            "threshold for coherence; rescues are flagged "
            "ngram_rescued=True in the evidence log."
        ),
        rephrases=(
            "why does the rescue skip bit symmetry?",
            "how does ngram rescue stage-vi work?",
            "explain stage vi for rescued entries",
        ),
    ),
    Seed(
        prompt="What is the rewired mode?",
        reply=(
            "--rewired disables seed-corpus prewarming and tunes the "
            "rewired manifest: runner_backend=native_full, "
            "coherence_lane=max-throughput, zpm_threshold_bits=28, "
            "omega_candidates=12, omega_budget_ms=12.0. It prefers "
            "live-learned cache over generic seeds."
        ),
        rephrases=(
            "what does --rewired do?",
            "explain rewired chat mode",
            "how is rewired different from fast-chat?",
        ),
    ),
    Seed(
        prompt="What is the Omega probe?",
        reply=(
            "The Omega probe projects the intent anchor onto every "
            "sub-lattice in the LMO router graph, runs a bounded "
            "evolution (inversion + rotor per sub-lattice), and folds "
            "the per-sub-lattice digests into a 256-bit candidate "
            "continuation state."
        ),
        rephrases=(
            "how does the omega probe work?",
            "explain the omega native probe",
            "what does _run_omega_probe do?",
        ),
    ),
    Seed(
        prompt="What does omega_budget_ms control?",
        reply=(
            "omega_budget_ms bounds the wall-clock time R2 spends on "
            "the Omega probe per turn. When exceeded, the probe stops "
            "early and demotes with reason budget_exceeded. The "
            "rewired default is 12ms."
        ),
        rephrases=(
            "what is omega_budget_ms?",
            "how does the omega budget work?",
            "explain omega budget milliseconds",
        ),
    ),
    Seed(
        prompt="What is effective_wps?",
        reply=(
            "effective_wps = total_words / wall_clock_s including "
            "cache-served turns. It is distinct from executed_wps "
            "(novel decode throughput) and cache_wps. effective_wps is "
            "the release gate metric."
        ),
        rephrases=(
            "explain effective wps",
            "how is effective_wps computed?",
            "what's the difference between effective wps and executed wps?",
        ),
    ),
    Seed(
        prompt="What does prompt_head metadata do in ZPM?",
        reply=(
            "prompt_head is the first 256 bytes of the prompt that "
            "produced a ZPM entry, stamped by R5 writeback. The n-gram "
            "rescue path ranks entries by char-3-gram Jaccard between "
            "prompt_head and the current query to find rephrasings of "
            "stored prompts."
        ),
        rephrases=(
            "what is prompt_head?",
            "how does zpm prompt_head metadata work?",
            "explain the prompt head field",
        ),
    ),
    Seed(
        prompt="What is the native_full backend?",
        reply=(
            "native_full moves R0, R1, and R2 candidate generation "
            "into native C code. R5 stays behind a Python callback "
            "bridge to libllama. It preserves byte-identical evidence "
            "logs against the python ladder."
        ),
        rephrases=(
            "explain native full backend",
            "what does runner_backend=native_full do?",
            "how does the native full hot path work?",
        ),
    ),
    Seed(
        prompt="How are muscle memory keys derived?",
        reply=(
            "_muscle_memory_key hashes the rendered prompt bundle with "
            "FNV-1a64. The bundle is "
            "model_sha|system|history|user|sampler, identical to the "
            "ZPM anchor input. The cache file is "
            "cache/mm/<model_sha>/<key:016x>.mm."
        ),
        rephrases=(
            "how does muscle memory keying work?",
            "what hash does muscle memory use?",
            "explain the mm key derivation",
        ),
    ),
    Seed(
        prompt="What does the rewired footer show?",
        reply=(
            "Each turn prints a one-line footer with the badge "
            "([Instant Map] for R2 exact, [Omega Rescue] for R2 n-gram "
            "rescue with overlap score, [ZPM Direct] for R1, [Muscle "
            "Memory] for R0, [Decode] for R5), token count, wall time, "
            "TPS, and effective_wps."
        ),
        rephrases=(
            "what's in the chat turn footer?",
            "explain the rewired footer badges",
            "how to read the footer output",
        ),
    ),
    Seed(
        prompt="What coherence guarantee does ngram rescue provide?",
        reply=(
            "N-gram rescue is surface-overlap-gated near-match service. "
            "The overlap threshold (char-3-gram Jaccard >= 0.30) gates "
            "admission, the rescue Stage-VI audit keeps tokenizer/UTF-8/"
            "blob checks, but bit-symmetry is skipped because rescued "
            "states differ from stored states by construction."
        ),
        rephrases=(
            "what does ngram rescue guarantee?",
            "how does rescue stay coherent?",
            "what's the coherence contract on rescued turns?",
        ),
    ),
)


# --------------------------------------------------------------------------- #
# Minimal GGUF fixture (identical to the test fixture; duplicated here
# so this script stands alone with no test-tree imports).
# --------------------------------------------------------------------------- #

_GGUF_TYPE_F32 = 0
_GGUF_VAL_UINT32 = 4
_GGUF_VAL_STRING = 8


def _wstr(buf: bytearray, s: bytes | str) -> None:
    data = s.encode("utf-8") if isinstance(s, str) else s
    buf += struct.pack("<Q", len(data))
    buf += data


def _kv_u32(buf: bytearray, key: str, value: int) -> None:
    _wstr(buf, key)
    buf += struct.pack("<I", _GGUF_VAL_UINT32)
    buf += struct.pack("<I", int(value) & 0xFFFFFFFF)


def _kv_str(buf: bytearray, key: str, value: str) -> None:
    _wstr(buf, key)
    buf += struct.pack("<I", _GGUF_VAL_STRING)
    _wstr(buf, value)


def _wtinfo(
    buf: bytearray, name: str, shape: tuple[int, ...],
    ggml_type: int, rel_offset: int,
) -> None:
    _wstr(buf, name)
    buf += struct.pack("<I", len(shape))
    for d in shape:
        buf += struct.pack("<Q", int(d))
    buf += struct.pack("<I", int(ggml_type))
    buf += struct.pack("<Q", int(rel_offset))


def _align(x: int, a: int) -> int:
    return (x + a - 1) & ~(a - 1)


def _build_fixture_gguf(path: Path, n_blocks: int = 2) -> None:
    alignment = 32
    tensors: list[tuple[str, tuple[int, ...]]] = [("token_embd.weight", (16,))]
    for i in range(n_blocks):
        tensors.append((f"blk.{i}.attn_q.weight", (8,)))
    tensors.append(("output.weight", (16,)))
    kv_buf = bytearray()
    _kv_u32(kv_buf, "general.alignment", alignment)
    _kv_str(kv_buf, "general.architecture", "llama")
    _kv_str(kv_buf, "tokenizer.ggml.model", "llama")
    _kv_str(kv_buf, "tokenizer.ggml.bos_token", "<s>")
    rel: list[int] = []
    cursor = 0
    tinfo = bytearray()
    for _n, shape in tensors:
        rel.append(cursor)
        n = 1
        for d in shape:
            n *= d
        cursor += n * 4
        cursor = _align(cursor, alignment)
    for (name, shape), ro in zip(tensors, rel):
        _wtinfo(tinfo, name, shape, _GGUF_TYPE_F32, ro)
    head = bytearray()
    head += b"GGUF"
    head += struct.pack("<I", 3)
    head += struct.pack("<Q", len(tensors))
    head += struct.pack("<Q", 4)
    pre = bytes(head) + bytes(kv_buf) + bytes(tinfo)
    data_start = _align(len(pre), alignment)
    buf = bytearray(max(data_start, len(pre)) + cursor)
    buf[: len(pre)] = pre
    for (_n, shape), ro in zip(tensors, rel):
        n = 1
        for d in shape:
            n *= d
        floats = [((i + 1) * 0.5) for i in range(n)]
        packed = struct.pack("<" + "f" * n, *floats)
        off = data_start + ro
        buf[off: off + len(packed)] = packed
    last_n = 1
    for d in tensors[-1][1]:
        last_n *= d
    end = data_start + rel[-1] + last_n * 4
    path.write_bytes(bytes(buf[:end]))


# --------------------------------------------------------------------------- #
# Bench kernel
# --------------------------------------------------------------------------- #


@dataclass
class RescueRecord:
    """Per-query outcome for the audit trail."""

    seed_prompt: str
    query: str
    served: bool
    ngram_rescued: bool
    overlap: float
    distance_bits: int
    matched_prompt_head: str
    matched_reply_head: str
    demotion_reasons: tuple[str, ...] = ()


@dataclass
class RescueBenchReport:
    """Summary + audit trail."""

    total_queries: int
    total_seeds: int
    total_rephrases: int
    served_total: int
    rescued_total: int
    # share = served / total_queries. rescue_share = rescued / served.
    served_share: float
    rescue_share: float
    # overlap distribution on rescued queries
    overlap_min: float = 0.0
    overlap_p50: float = 0.0
    overlap_max: float = 0.0
    audit: list[RescueRecord] = field(default_factory=list)

    def to_dict(self) -> dict[str, object]:
        d = {
            "total_queries": self.total_queries,
            "total_seeds": self.total_seeds,
            "total_rephrases": self.total_rephrases,
            "served_total": self.served_total,
            "rescued_total": self.rescued_total,
            "served_share": self.served_share,
            "rescue_share": self.rescue_share,
            "overlap_min": self.overlap_min,
            "overlap_p50": self.overlap_p50,
            "overlap_max": self.overlap_max,
            "audit": [r.__dict__ for r in self.audit],
        }
        return d


def _percentile(xs: list[float], p: float) -> float:
    if not xs:
        return 0.0
    s = sorted(xs)
    k = int(round((p / 100.0) * (len(s) - 1)))
    return s[max(0, min(len(s) - 1, k))]


def _seed_zpm_for_corpus(
    manifest: gguf.GgufManifest,
    corpus: tuple[Seed, ...],
) -> zpm.ZpmIndex:
    """Build an in-memory ZPM index with one entry per seed.

    The state is computed with the same anchor convention the live R5
    writeback path in ``gguf.py`` uses -- ``zpm.anchor(_zpm_anchor_bytes(...))``
    -- so this faithfully models what a real chat session accumulates.
    The prompt_head metadata is stamped identically as well. The index
    is kept in memory only; we never touch the user's on-disk ZPM
    cache.
    """
    idx = zpm.ZpmIndex()
    for seed in corpus:
        state = zpm.anchor(gguf._zpm_anchor_bytes(manifest, seed.prompt))
        idx.add(
            zpm.ZpmEntry(
                state=state,
                reply_text=seed.reply,
                tokens=max(1, len(seed.reply.split())),
                wall_s_at_write=0.0001,
                metadata={
                    "model": Path(manifest.model).name,
                    "chat_format": manifest.chat_format,
                    "seed": str(manifest.seed),
                    "prompt_head": seed.prompt[:256],
                    "src": "r2_rescue_bench",
                },
            )
        )
    return idx


def _run_bench(
    *,
    model_path: Path,
    nrl_root: Path,
    corpus: tuple[Seed, ...],
    zpm_threshold_bits: int,
    omega_budget_ms: float,
    verbose: bool,
) -> RescueBenchReport:
    # Absorb the GGUF into an LMO handle. ``absorb_gguf`` is content-
    # addressed on ``sha256(gguf)`` so a previously-absorbed model is
    # a fast cache hit; a first absorption of a multi-GB model is
    # proportional to disk-read throughput and is a one-time cost.
    print(f"  [bench] absorbing LMO from {model_path.name} ...", flush=True)
    t_absorb = time.perf_counter()
    absorbed = lmo.absorb_gguf(model_path, attempt_libllama=False)
    print(
        f"  [bench] LMO ready in {time.perf_counter() - t_absorb:.2f}s "
        f"(sha={absorbed.header.model_sha256[:12]}...)",
        flush=True,
    )

    # Build a throwaway manifest anchored to the same model. We skip
    # the ``run_gguf`` bootstrap -- that would trigger a real decode
    # against libllama for a 2 GB model -- and compute the model sha
    # directly. Every helper in this script only needs the sha and
    # manifest-level anchor bytes; neither needs a live decoder.
    manifest = gguf.manifest_from_args(
        str(model_path),
        prompt="bench-bootstrap",
        max_tokens=3,
        seed=1,
        muscle_memory="off",
        coherence_lane="max-throughput",
        r2_shadow_enabled=True,
        omega_budget_ms=omega_budget_ms,
    )
    # zpm_threshold_bits is not accepted by manifest_from_args; set it
    # post-construction (same pattern as rewired-mode's zpm_nullspace).
    manifest.zpm_threshold_bits = int(zpm_threshold_bits)
    # Populate model_sha256 directly -- no decode needed.
    manifest.model_sha256 = absorbed.header.model_sha256

    zidx = _seed_zpm_for_corpus(manifest, corpus)

    audit: list[RescueRecord] = []
    served = 0
    rescued = 0
    overlaps: list[float] = []
    total_rephrases = 0

    for seed in corpus:
        for rephrase in seed.rephrases:
            total_rephrases += 1
            intent_bytes = gguf._zpm_anchor_bytes(manifest, rephrase)
            rung, rep = try_omega_native_resolve(
                absorbed,
                intent_anchor_bytes=intent_bytes,
                coherence_lane="max-throughput",
                zpm_index=zidx,
                zpm_threshold_bits=zpm_threshold_bits,
                omega_budget_ms=omega_budget_ms,
                mode="active",
                prompt_text=rephrase,
            )
            matched_head = ""
            matched_reply = ""
            if rep.stored_entry_index >= 0:
                entries = list(zidx)
                if 0 <= rep.stored_entry_index < len(entries):
                    e = entries[rep.stored_entry_index]
                    matched_head = e.metadata.get("prompt_head", "")
                    matched_reply = e.reply_text[:120]
            rec = RescueRecord(
                seed_prompt=seed.prompt,
                query=rephrase,
                served=rep.served,
                ngram_rescued=rep.ngram_rescued,
                overlap=rep.ngram_best_overlap,
                distance_bits=rep.zpm_distance_bits,
                matched_prompt_head=matched_head,
                matched_reply_head=matched_reply,
                demotion_reasons=rep.demotion_reasons,
            )
            audit.append(rec)
            if rep.served:
                served += 1
            if rep.ngram_rescued:
                rescued += 1
                overlaps.append(rep.ngram_best_overlap)
            if verbose:
                print(
                    f"  seed={seed.prompt[:40]!r:<44}  query={rephrase[:40]!r:<44}  "
                    f"served={rep.served} rescued={rep.ngram_rescued} "
                    f"overlap={rep.ngram_best_overlap:.2f}"
                )

    total_queries = total_rephrases
    return RescueBenchReport(
        total_queries=total_queries,
        total_seeds=len(corpus),
        total_rephrases=total_rephrases,
        served_total=served,
        rescued_total=rescued,
        served_share=(served / total_queries) if total_queries else 0.0,
        rescue_share=(rescued / served) if served else 0.0,
        overlap_min=min(overlaps) if overlaps else 0.0,
        overlap_p50=_percentile(overlaps, 50.0),
        overlap_max=max(overlaps) if overlaps else 0.0,
        audit=audit,
    )


def _format_report(r: RescueBenchReport, *, show_audit: bool) -> str:
    lines: list[str] = []
    lines.append("=" * 78)
    lines.append("NRL Phase 11 — R2 Omega n-gram rescue benchmark")
    lines.append(f"  seeds                   : {r.total_seeds}")
    lines.append(f"  rephrased queries       : {r.total_queries}")
    lines.append(f"  overlap threshold       : {_NGRAM_OVERLAP_THRESHOLD:.2f}")
    lines.append("-" * 78)
    lines.append(
        f"  served_total            : {r.served_total} of {r.total_queries}  "
        f"({100.0 * r.served_share:.1f}% served share)"
    )
    lines.append(
        f"  ngram_rescued_total     : {r.rescued_total} of {r.served_total}  "
        f"({100.0 * r.rescue_share:.1f}% of served via rescue)"
    )
    if r.rescued_total > 0:
        lines.append(
            f"  overlap min/p50/max     : "
            f"{r.overlap_min:.2f} / {r.overlap_p50:.2f} / {r.overlap_max:.2f}"
        )
    lines.append("=" * 78)

    if show_audit:
        lines.append("")
        lines.append("Per-query audit (query -> matched prompt_head -> reply head):")
        lines.append("-" * 78)
        for rec in r.audit:
            status = (
                "RESCUED" if rec.ngram_rescued
                else "SERVED " if rec.served
                else "DEMOTED"
            )
            lines.append(
                f"  [{status}] query={rec.query!r}"
            )
            if rec.served or rec.ngram_rescued:
                lines.append(
                    f"    -> prompt_head={rec.matched_prompt_head!r}"
                )
                lines.append(
                    f"    -> reply_head ={rec.matched_reply_head!r}"
                )
                lines.append(
                    f"    -> overlap={rec.overlap:.2f}  "
                    f"distance={rec.distance_bits}b"
                )
            else:
                lines.append(
                    f"    -> demoted reasons: {', '.join(rec.demotion_reasons)}"
                )
            lines.append("")
        lines.append("=" * 78)
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        prog="r2_rescue_bench",
        description=(
            "Audit R2 Omega n-gram rescue quality on a curated NRL Q&A "
            "corpus. Measures rescue fire-rate, overlap distribution, "
            "and prints the prompt_head/reply audit trail."
        ),
    )
    ap.add_argument(
        "--model",
        type=Path,
        default=None,
        help=(
            "Path to a GGUF file. If omitted, a tiny self-contained "
            "fixture is used (sufficient for the rescue logic audit; "
            "NOT for throughput numbers -- use `nrlpy bench-wps` for "
            "those)."
        ),
    )
    ap.add_argument(
        "--zpm-threshold-bits",
        type=int,
        default=28,
        help="Hamming tolerance for ZPM primary lookup. Default: 28 (rewired).",
    )
    ap.add_argument(
        "--omega-budget-ms",
        type=float,
        default=12.0,
        help="Omega probe wall budget. Default: 12.0ms (rewired).",
    )
    ap.add_argument(
        "--audit",
        action="store_true",
        help="Print the full per-query audit trail.",
    )
    ap.add_argument(
        "--json",
        action="store_true",
        help="Emit the full report as JSON.",
    )
    ap.add_argument(
        "--verbose",
        action="store_true",
        help="Print one line per query while running.",
    )
    args = ap.parse_args(argv)

    import os
    import tempfile

    tmp = Path(tempfile.mkdtemp(prefix="nrl_r2_rescue_bench_"))

    if args.model is None:
        # Fixture mode: isolate NRL_ROOT to the tmpdir and force stub
        # inference so the test fixture never tries real decode.
        os.environ["NRL_ROOT"] = str(tmp)
        os.environ["NRL_INFERENCE"] = "stub"
        fx = tmp / "fixture.gguf"
        _build_fixture_gguf(fx, n_blocks=2)
        model_path = fx
    else:
        # Real-model mode: respect the user's existing NRL_ROOT so the
        # LMO cache hits on repeat runs (absorption is content-
        # addressed; a first absorption of a multi-GB GGUF is the slow
        # step). The ZPM index is built in memory only, never written
        # to the user's on-disk cache.
        model_path = args.model
        if not model_path.is_file():
            print(f"error: model not found: {model_path}", file=sys.stderr)
            return 2

    t0 = time.perf_counter()
    report = _run_bench(
        model_path=model_path,
        nrl_root=tmp,
        corpus=_SEED_CORPUS,
        zpm_threshold_bits=args.zpm_threshold_bits,
        omega_budget_ms=args.omega_budget_ms,
        verbose=args.verbose,
    )
    elapsed = time.perf_counter() - t0

    if args.json:
        out = report.to_dict()
        out["wall_clock_s"] = elapsed
        out["nrl_root"] = str(tmp)
        out["model_path"] = str(model_path)
        print(json.dumps(out, indent=2, default=str))
    else:
        print(_format_report(report, show_audit=args.audit))
        print(f"  wall_clock_s            : {elapsed:.3f}")
        print(f"  nrl_root (isolated)     : {tmp}")
        print(f"  model_path              : {model_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
