"""Type stubs for nrlpy._core."""

from __future__ import annotations

from typing import Any

class NrlPyError(Exception): ...

__version__: str

def init() -> None: ...
def version() -> str: ...
def features() -> dict[str, bool]: ...
def active_variant(name: str) -> str: ...
def braincore_packed_bytes(neurons: int) -> int: ...

def braincore_int4_inplace(
    potentials: Any,
    inputs: Any,
    neurons: int,
    iterations: int,
    threshold: int,
) -> dict[str, Any]: ...

def braincore_int4(
    neurons: int = ..., iterations: int = ..., threshold: int = ...
) -> dict[str, Any]: ...
